apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb-deployment
  labels:
    app: serviceb
    refresh: ossi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serviceb
      refresh: ossi
  template:
    metadata:
      labels:
        app: serviceb
        refresh: ossi
    spec:
      containers:
      - name: serviceb
        image: servicb:0.0.14-SNAPSHOT
        ports:
        - containerPort: 8020
      initContainers:
      - name: init-myservice
        image: busybox
        command: ['sh', '-c', 'until nslookup configserver; do echo waiting for myservice; sleep 2; done;']
