apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea-deployment
  labels:
    app: servicea
    refresh: ossi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servicea
      refresh: ossi
  template:
    metadata:
      labels:
        app: servicea
        refresh: ossi
    spec:
      containers:
      - name: servicea
        env:
        - name: eureka.instance.hostname
          value: "eureka-server"
        - name: PORT
          value: "80"
        image: servica:0.0.12-SNAPSHOT
        ports:
        - containerPort: 8010
