apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea-deployment
  labels:
    app: servicea
    refresh: ossi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servicea
      refresh: ossi
  template:
    metadata:
      labels:
        app: servicea
        refresh: ossi
    spec:
      containers:
      - name: servicea
        image: servica:0.0.12-SNAPSHOT
        ports:
        - containerPort: 8010
      initContainers:
      - name: init-myservice
        image: busybox
        command: ['sh', '-c', 'until nslookup configserver; do echo waiting for myservice; sleep 2; done;']
